BAU: Fix whitespace error
This change fixes the following error message by removing export from local-vsp-only.env. Please see the issue (https://github.com/docker/compose/issues/6838). According to Docker documentation, there is no need to have export in the environment file (Source: https://docs.docker.com/compose/compose-file/#env_file#env_file).

ERROR: In file /tmp/build/a94a8fe5/passport-verify-stub/local-vsp-only.env: environment variable name 'export SERVICE_ENTITY_IDS' may not contains whitespace.

Author: @adityapahuja